version: '3.8'
services:
  agentic-rag:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY} 